services:
  postgres:
    image: postgres:15-alpine
    container_name: chat_postgres
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  auth-service:
    build:
      context: .
      dockerfile: packages/auth-service/Dockerfile
    container_name: auth_service
    environment:
      - PORT=4001
      - DATABASE_URL=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB}?schema=public
      - JWT_SECRET=${JWT_SECRET}
      - FRONTEND_URL=${FRONTEND_URL}
      - MESSAGE_SERVICE_URL=${MESSAGE_SERVICE_URL}
    depends_on:
      - postgres

  user-service:
    build:
      context: .
      dockerfile: packages/user-service/Dockerfile
    container_name: user_service
    environment:
      - PORT=4003
      - DATABASE_URL=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB}?schema=public
      - JWT_SECRET=${JWT_SECRET}
      - FRONTEND_URL=${FRONTEND_URL}
    depends_on:
      - postgres

  message-service:
    build:
      context: .
      dockerfile: packages/message-service/Dockerfile
    container_name: message_service
    environment:
      - PORT=4002
      - DATABASE_URL=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB}?schema=public
      - JWT_SECRET=${JWT_SECRET}
      - CLOUDINARY_CLOUD_NAME=${CLOUDINARY_CLOUD_NAME}
      - CLOUDINARY_API_KEY=${CLOUDINARY_API_KEY}
      - CLOUDINARY_API_SECRET=${CLOUDINARY_API_SECRET}
      - FRONTEND_URL=${FRONTEND_URL}
      - CLIENT_ORIGIN=${FRONTEND_URL}
    depends_on:
      - postgres

  web-client:
    build:
      context: .
      dockerfile: packages/web-client/Dockerfile
    container_name: web_client
    ports:
      - "80:80"
    depends_on:
      - auth-service
      - message-service
      - user-service

volumes:
  postgres_data: